blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from django.views.decorators.cache import cache_page
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', cache_page(5 * 60)(BlogCreateView.as_view()), name='create'),
    path('', cache_page(5 * 60)(BlogListView.as_view()), name='list'),
    path('view/<int:pk>/', cache_page(5 * 60)(BlogDetailView.as_view()), name='view'),
    path('edit/<int:pk>/', cache_page(5 * 60)(BlogUpdateView.as_view()), name='edit'),
    path('delete/<int:pk>/', cache_page(5 * 60)(BlogDeleteView.as_view()), name='delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('main.urls', namespace='main')),
                  path('users/', include('users.urls', namespace='users')),
                  path('blog/', include('blog.urls', namespace='blog')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.conf import settings


NULLABLE = {'blank': True, 'null': True}  # шаблон для необязательного элемента


class Blog(models.Model):
    title = models.CharField(max_length=150, verbose_name='заголовок')
    body = models.TextField(verbose_name='содержимое')
    preview = models.ImageField(upload_to='blog/', verbose_name='изображение', **NULLABLE)
    published_date = models.DateTimeField(auto_now=True, verbose_name='дата публикации')
    view_count = models.IntegerField(default=0, verbose_name='просморы')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE,
                             verbose_name='Пользователь')

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'блог'
        verbose_name_plural = 'блоги'

blog/forms.py
from django import forms
from blog.models import Blog


class BlogForm(forms.ModelForm):  # Форма под создание екземпляра продукта

    class Meta:
        model = Blog
        # fields = '__all__' можно так (выбрать все поля)
        fields = ('title', 'body', 'preview')
        # exclude = ('is_active', ...,...)  + это (исключить)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from blog.models import Blog
from blog.forms import BlogForm
from django.conf import settings
from django.core.cache import cache


class BlogCreateView(LoginRequiredMixin, CreateView):
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy('blog:list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Создание блога'

        return context

    def form_valid(self, form):
        """
        Для автоматического выставления хозяина при регистрации нового пользователя
        :param form:
        :return:
        """
        self.object = form.save()
        self.object.user = self.request.user
        self.object.save()

        return super().form_valid(form)


class BlogUpdateView(LoginRequiredMixin, UpdateView):
    model = Blog
    form_class = BlogForm

    def get_success_url(self):
        return reverse('blog:view', args=[self.kwargs.get('pk')])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f'Изменение "{self.object.title}"'

        return context


class BlogListView(LoginRequiredMixin, ListView):
    model = Blog

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if settings.CACHE_ENABLED:
            key = f'big_blog_list'
            blog_list = cache.get(key)
            if blog_list is None:
                blog_list = Blog.objects.all()
                cache.set(key, blog_list)
            else:
                blog_list = Blog.objects.all()

        context['object'] = blog_list
        context['title'] = 'Блог'

        return context


class BlogDetailView(LoginRequiredMixin, DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.view_count += 1
        self.object.save()

        return self.object

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.object.title

        return context


class BlogDeleteView(LoginRequiredMixin, DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f'Удаление "{self.object.title}"'

        return context

blog/templates/blog/blog_confirm_delete.html
{% extends 'main/base.html' %}
{% load img_tag %}
{% block content %}
<div class="col-12 mx-auto d-flex justify-content-center align-items-center">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Удалить блог "{{object.title|title}}"?</p>
                        <button type="submit" class="btn btn-success">
                            Подтвердить
                        </button>
                        <a href="{% url 'blog:list' %}" class="btn btn-danger">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'main/base.html' %}
{% load img_tag %}
{% block content %}
<div class="col-4 mx-auto d-flex justify-content-center align-items-center">
    <div class="card mb-4 box-shadow">
        <div class="card-header">
            <img src="/media/{{ object.preview }}" style="width:100%; height:300px;"/>
            <h3 class="my-0 font-weight-normal text-center">{{ object.title | title }} </h3>
        </div>
        <div class="card-body">
            <p>{{object.body | title}} </p>
            <p>{{ object.published_date }} </p>
            <p>Автор: {{object.user}} </p>
            <p>Просмотры: {{object.view_count}}</p>
            <br>
            {%if object.user == user or user.is_staff%}
            <a class="btn btn-outline-primary" href="{% url 'blog:edit' object.pk %}">Редактировать запись</a>
            <br>
            <a href="{% url 'blog:delete' object.pk %}" type="button"
               class="btn btn-sm btn-outline-danger">Удалить</a>
            <br>
            {%endif%}
            <a href="{% url 'blog:list'%}" class="btn btn-outline-primary">Назад</a>

        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'main/base.html' %}
{% load img_tag %}
{% block content %}
<div class="col-12 d-flex justify-content-center">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <a href="{% url 'blog:list'%}" type="button"
                           class="btn btn-outline-primary">Назад</a>
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                            Обновить
                            {% else %}
                            Создать
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'main/base.html' %}
{% load img_tag %}
{% block content %}
<div class="row text-center" style="margin: 0 35px;">
    <p class="lead">Блог</p>
    <div class="row text-center">

        {% if not user.is_staff or user.is_superuser %}
        <a class="btn btn-primary" href="{% url 'blog:create' %}">Добавить запись</a>
        {% endif %}

        <br>
        {% for object in object_list %}
        <div class="col-3">
            <br>
            <div class="card mb-4 box-shadow">

                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.title | title }}</h4>
                    <img src="/media/{{ object.preview }}" style="width:200px; height:150px;"/>
                </div>

                <div class="card-body">
                    <a class="card-title">{{object.body}}</a>
                    <br>
                    <br>
                    <a href="{% url 'blog:view' object.pk %}" type="button"
                       class="btn btn-outline-primary text-center">Посмотреть</a>
                    <br>
                    {%if object.user == user or user.is_staff%}
                    <a href="{% url 'blog:edit' object.pk %}" type="button"
                       class="btn btn-outline-primary">Редактировать</a>
                    <br>
                    <a href="{% url 'blog:delete' object.pk %}" type="button"
                       class="btn btn-outline-danger">Удалить</a>
                    {%endif%}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}