blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from django.views.decorators.cache import cache_page
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', cache_page(5 * 60)(BlogCreateView.as_view()), name='create'),
    path('', cache_page(5 * 60)(BlogListView.as_view()), name='list'),
    path('view/<int:pk>/', cache_page(5 * 60)(BlogDetailView.as_view()), name='view'),
    path('edit/<int:pk>/', cache_page(5 * 60)(BlogUpdateView.as_view()), name='edit'),
    path('delete/<int:pk>/', cache_page(5 * 60)(BlogDeleteView.as_view()), name='delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('main.urls', namespace='main')),
                  path('users/', include('users.urls', namespace='users')),
                  path('blog/', include('blog.urls', namespace='blog')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from main.apps import MainConfig
from django.views.decorators.cache import cache_page
from main.views import index, UserListView, UserDetailView, MassageListView, MassageDetailView, MassageCreateView, \
    MassageUpdateView, UserUpdateView, MassageDeleteView, SettingsReportListView, ClientListView, ClientDetailView, \
    ClientCreateView, ClientUpdateView, \
    ClientDeleteView, SettingsListView, SettingsDetailView, SettingsCreateView, SettingsUpdateView, SettingsDeleteView

app_name = MainConfig.name

urlpatterns = [
    path('', cache_page(5 * 60)(index), name='index'),
    path('users_list/', cache_page(5 * 60)(UserListView.as_view()), name='users_list'),
    path('user/view/<int:pk>/', cache_page(5 * 60)(UserDetailView.as_view()), name='user_view'),
    path('user/edit/<int:pk>/', cache_page(5 * 60)(UserUpdateView.as_view()), name='user_update'),
    path('report/', cache_page(5 * 60)(SettingsReportListView.as_view()), name='report'),
    path('massages/', cache_page(5 * 60)(MassageListView.as_view()), name='massage_list'),
    path('massage/view/<int:pk>/', cache_page(5 * 60)(MassageDetailView.as_view()), name='massage_view'),
    path('massage/create/', cache_page(5 * 60)(MassageCreateView.as_view()), name='massage_create'),
    path('massage/edit/<int:pk>/', cache_page(5 * 60)(MassageUpdateView.as_view()), name='massage_update'),
    path('massage/delete/<int:pk>/', cache_page(5 * 60)(MassageDeleteView.as_view()), name='massage_delete'),
    path('clients/', cache_page(5 * 60)(ClientListView.as_view()), name='client_list'),
    path('client/view/<int:pk>/', cache_page(5 * 60)(ClientDetailView.as_view()), name='client_view'),
    path('client/create/', cache_page(5 * 60)(ClientCreateView.as_view()), name='client_create'),
    path('client/edit/<int:pk>/', cache_page(5 * 60)(ClientUpdateView.as_view()), name='client_update'),
    path('client/delete/<int:pk>/', cache_page(5 * 60)(ClientDeleteView.as_view()), name='client_delete'),
    path('settings/', cache_page(5 * 60)(SettingsListView.as_view()), name='settings_list'),
    path('settings/view/<int:pk>/', cache_page(5 * 60)(SettingsDetailView.as_view()), name='settings_view'),
    path('settings/create/', cache_page(5 * 60)(SettingsCreateView.as_view()), name='settings_create'),
    path('settings/edit/<int:pk>/', cache_page(5 * 60)(SettingsUpdateView.as_view()), name='settings_update'),
    path('settings/delete/<int:pk>/', cache_page(5 * 60)(SettingsDeleteView.as_view()), name='settings_delete')
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import RegisterView, ProfileView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
]

main/models.py
from django.db import models
from datetime import datetime
from django.conf import settings

NULLABLE = {'blank': True, 'null': True}  # шаблон для необязательного элемента


class Logs(models.Model):
    STATUS_TYPES = [
        ('start', 'Запущена'),
        ('finish', 'Завершена'),
        ('created', 'Создана')
    ]

    datatime = models.DateTimeField(verbose_name='Время и дата последней попытки', auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_TYPES, default='created', verbose_name='Статус')
    response = models.CharField(max_length=100, verbose_name='Ответ сервера', )

    def __str__(self):
        return f'{self.status}, {self.response}, {self.datatime}'

    class Meta:
        verbose_name = 'Логи'
        verbose_name_plural = 'Логи'


class Massage(models.Model):
    head = models.CharField(max_length=150, verbose_name='Тема письма')
    body = models.TextField(verbose_name='Тело письма')
    logs = models.ManyToManyField(Logs, verbose_name='Логи', **NULLABLE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE,
                             verbose_name='Пользователь')

    def __str__(self):
        return f'{self.head}'

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'


class Client(models.Model):
    first_name = models.CharField(max_length=150, verbose_name='Имя', **NULLABLE)
    last_name = models.CharField(max_length=150, verbose_name='Фамилия', **NULLABLE)
    sur_name = models.CharField(max_length=150, verbose_name='Отчество', **NULLABLE)
    mail = models.EmailField(unique=True, verbose_name='Почта')
    description = models.TextField(verbose_name='Описание', **NULLABLE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE,
                             verbose_name='Пользователь')

    def __str__(self):
        return f'{self.mail}'

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'


class Settings(models.Model):
    STATUS_TYPES = [
        ('start', 'Запущена'),
        ('finish', 'Завершена'),
        ('created', 'Создана')
    ]

    FREQUENCY_TYPES = [
        ('once_a_day', 'Раз в день'),
        ('once_a_week', 'Раз в неделю'),
        ('once_a_month', 'Раз в месяц')
    ]

    time = models.DateTimeField(verbose_name='Время рассылки', default=datetime.now())
    frequency = models.CharField(default='Раз в день', choices=FREQUENCY_TYPES, verbose_name='Периодичность')
    status = models.CharField(max_length=10, default='start', choices=STATUS_TYPES, verbose_name='Статус')
    client = models.ManyToManyField(Client, verbose_name='Клиенты', )
    massage = models.ManyToManyField(Massage, verbose_name='Письма', )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE,
                             verbose_name='Пользователь')

    def __str__(self):
        return f'{self.time}, {self.frequency}, {self.status}'

    class Meta:
        verbose_name = 'Настройка'
        verbose_name_plural = 'Настройки'

main/forms.py
from django import forms
from main.models import Massage, Client, Settings


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

main/views.py
from django.shortcuts import render
from main.models import Massage, Client, Settings
from django.urls import reverse_lazy, reverse
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from blog.models import Blog
from users.models import User
from django.conf import settings
from django.core.cache import cache


@login_required
def index(request):
    if settings.CACHE_ENABLED:
        key = f'blog_list'
        blog_list = cache.get(key)
        if blog_list is None:
            blog_list = Blog.objects.all()[:3]
            cache.set(key, blog_list)
        else:
            blog_list = Blog.objects.all()[:3]

    all_massage = Massage.objects.count()
    active_massage = Settings.objects.filter(status='start')
    all_client = Client.objects.count()
    context = {
        'title': 'Главная',
        'all_massage': all_massage,
        'active_massage': active_massage.count(),
        'all_client': all_client,
        'blog': blog_list,
    }

    return render(request, 'main/index.html', context)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    template_name = 'main/users_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Пользователи'

        return context


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    template_name = 'main/user_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f'{self.object.email}'

        return context


class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    fields = ('is_active',)

    def get_success_url(self):
        return reverse('main:user_view', args=[self.kwargs.get('pk')])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = f'Изменение "{self.object.email}"'

        return context_data


class SettingsReportListView(LoginRequiredMixin, ListView):
    model = Settings
    template_name = 'main/report.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Отчет по рассылкам'

        return context


class MassageListView(LoginRequiredMixin, ListView):
    model = Massage
    template_name = 'main/massage_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Список сообщений'

        return context


class MassageDetailView(LoginRequiredMixin, DetailView):
    model = Massage
    template_name = 'main/massage_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.object.head

        return context


class MassageCreateView(LoginRequiredMixin, CreateView):
    model = Massage
    fields = ('head', 'body',)
    success_url = reverse_lazy('main:massage_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Создание сообщения'

        return context

    def form_valid(self, form):
        """
        Для автоматического выставления хозяина при регистрации нового пользователя
        :param form:
        :return:
        """
        self.object = form.save()
        self.object.user = self.request.user
        self.object.save()

        return super().form_valid(form)


class MassageUpdateView(LoginRequiredMixin, UpdateView):
    model = Massage
    fields = ('head', 'body',)

    def get_success_url(self):
        return reverse('main:massage_view', args=[self.kwargs.get('pk')])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = f'Изменение "{self.object.head}"'

        return context_data


class MassageDeleteView(LoginRequiredMixin, DeleteView):
    model = Massage
    success_url = reverse_lazy('main:massage_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f'Удаление "{self.object.head}"'

        return context


class ClientListView(LoginRequiredMixin, ListView):
    model = Client
    template_name = 'main/client_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Список клиентов'

        return context


class ClientDetailView(LoginRequiredMixin, DetailView):
    model = Client
    template_name = 'main/client_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.object.mail

        return context


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    fields = ('first_name', 'last_name', 'sur_name', 'mail', 'description',)
    success_url = reverse_lazy('main:client_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Запись клиента'

        return context

    def form_valid(self, form):
        """
        Для автоматического выставления хозяина при регистрации нового пользователя
        :param form:
        :return:
        """
        self.object = form.save()
        self.object.user = self.request.user
        self.object.save()

        return super().form_valid(form)


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    model = Client
    fields = ('first_name', 'last_name', 'sur_name', 'description',)

    def get_success_url(self):
        """
        Перенаправления после сохранения
        :return:
        """
        return reverse('main:client_view', args=[self.kwargs.get('pk')])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = f'Изменение "{self.object.mail}"'

        return context_data


class ClientDeleteView(LoginRequiredMixin, DeleteView):
    model = Client
    success_url = reverse_lazy('main:client_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f'Удаление "{self.object.mail}"'

        return context


class SettingsListView(LoginRequiredMixin, ListView):
    model = Settings
    template_name = 'main/settings_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Список настроек'

        return context


class SettingsDetailView(LoginRequiredMixin, DetailView):
    model = Settings
    template_name = 'main/settings_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.object.time

        return context


class SettingsCreateView(LoginRequiredMixin, CreateView):
    model = Settings
    fields = ('time', 'frequency', 'client', 'massage')
    success_url = reverse_lazy('main:settings_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Создание настройки'

        return context

    def form_valid(self, form):
        """
        Для автоматического выставления хозяина при регистрации нового пользователя
        :param form:
        :return:
        """
        self.object = form.save()
        self.object.user = self.request.user
        self.object.save()

        return super().form_valid(form)

    def get_form(self, form_class=None):
        """
        Было пипец как сложно до этого дойти, но у меня получилось
        эта функция фильтрует выборку клиентов и сообщения, на те, чей создатель - текущий пользователь
        + проверка на админа
        """
        form = super(SettingsCreateView, self).get_form(form_class)

        if not self.request.user.is_superuser:
            form.fields['client'].queryset = Client.objects.filter(user=self.request.user)
            form.fields['massage'].queryset = Massage.objects.filter(user=self.request.user)
            return form
        else:
            return form


class SettingsUpdateView(LoginRequiredMixin, UpdateView):
    model = Settings
    fields = ('time', 'frequency', 'client', 'massage')

    def get_success_url(self):
        return reverse('main:settings_view', args=[self.kwargs.get('pk')])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = f'Изменение настройки'

        return context_data

    def get_form(self, form_class=None):
        """
        Было пипец как сложно до этого дойти, но у меня получилось
        эта функция фильтрует выборку клиентов и сообщения, на те, чей создатель - текущий пользователь
        + проверка на админа
        """
        form = super(SettingsUpdateView, self).get_form(form_class)

        if not self.request.user.is_superuser:
            form.fields['client'].queryset = Client.objects.filter(user=self.request.user)
            form.fields['massage'].queryset = Massage.objects.filter(user=self.request.user)
            return form
        else:
            return form


class SettingsDeleteView(LoginRequiredMixin, DeleteView):
    model = Settings
    success_url = reverse_lazy('main:settings_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f'Удаление настройки'

        return context

main/templates/main/base.html
{% load static %}
{% load img_tag %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <style>
        body {display: flex; flex-direction: column; min-height: 100vh;}
        footer {margin-top: auto;}
    </style>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-dark text-light  p-4">
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="btn btn-primary btn-block mb-2" href="/">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="btn btn-info btn-block mb-2" href="{% url 'blog:list'%}">Блог</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link text-light" href="{% url 'users:profile'%}">Профиль</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:logout'%}" style="color: red;">Выйти</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link text-light" href="{% url 'users:register'%}">Регистрация</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-light" href="{% url 'users:login'%}">Войти</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
</header>
<br>

{% block content%}

{% endblock %}

<br>

<footer class="bg-dark text-light  p-4">
    &copy; 2023 - {% now 'Y' %} Auto_Mailing
</footer>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/bootstrap.esm.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

main/templates/main/client_detail.html
{% extends 'main/base.html' %}
{% block content %}
<div class="col-6 mx-auto d-flex justify-content-center align-items-center">
    <br>
    <div class="card mb-4 box-shadow">

        <div class="card-header">
            <h4 class="my-0 font-weight-normal text-center">{{ object.mail }}</h4>
        </div>

        <div class="card-body">
            <h4 class="card-title pricing-card-title text-center">{{object.first_name}} {{object.last_name}}</h4>
            <ul class="list-unstyled mt-3 mb-4 text-start m-3 text-center">
                <li>Описание:</li>
                <li>{{object.description}}</li>
                <li>Хозяин:</li>
                <li>{{object.user}}</li>
            </ul>

            <a href="{% url 'main:client_list'%}" type="button"
               class="btn btn-lg btn-block btn-outline-primary">Назад</a>

            {% if user.is_superuser or user == object.user %}
            <a href="{% url 'main:client_update' object.pk %}" type="button"
               class="btn btn-lg btn-block btn-outline-primary">Редактировать</a>
            <a href="{% url 'main:client_delete' object.pk %}" type="button"
               class="btn btn-lg btn-block btn-outline-danger">Удалить</a>
            {% endif %}

        </div>
    </div>
</div>
{% endblock %}

main/templates/main/client_list.html
{% extends 'main/base.html' %}
{% block content %}
<div class="jumbotron  text-center">
    <h1 class="display-3">Список клиентов</h1>
    <p class="lead"></p>

    <div class="container text-center">
        <br>
        <div class="row">
            <div class="col">
                <ul class="list-group">
                    {% for object in object_list %}
                    {%if object.user == user or user.is_staff%}
                    <li class="list-group-item">
                        <a type="button" class="btn btn-outline-primary btn-block mb-2" href="{% url 'main:client_view' object.pk %}" style="width:50%">
                            {{ object.mail }}
                        </a>
                    </li>
                    {%endif%}
                    {% endfor %}
                    {% if not user.is_staff or user.is_superuser %}
                     <li class="list-group-item">
                        <a type="button" class="btn btn-success btn-block mb-2" href="{% url 'main:client_create' %}" style="width:25%">Записать
                            клиента</a>
                    </li>
                    {%endif%}
                </ul>
                <a href="{% url 'main:index'%}" type="button"
               class="btn btn-lg btn-block btn-outline-primary">Назад</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}
{% block content %}
<div style="display: flex;">
    <div class="rol-12">
        <ul>
            <li>Всего рассылок: {{all_massage}}</li>
            <li>Активных рассылок: {{active_massage}}</li>
            <li>Количество клиентов: {{all_client}}</li>
        </ul>
    </div>
    <div class="rol-12" style="margin-left: 700px;">
        <ul class="message-list">
            {%for bl in blog%}
            <li class="message">
                <a type="button" class="btn btn-outline-primary" href="{% url 'blog:view' bl.pk %}"
                   style="width: 400px;">
                    <span style="font-size: 18px;">{{bl.title|slice:':20' }}...</span>
                    <br>
                    <span style="font-size: 18px;">{{bl.body|slice:':50'}}...</span>
                    <br>
                </a>
            </li>
            {%endfor%}
        </ul>
    </div>
</div>

<div class="text-center">
    <h1 class="display-3">Главная страница</h1>
    <p class="lead"></p>

    <div class="container text-center">
        <br>
        <div class="row">
            <div class="col">
                <ul class="list-group">
                    <li class="list-group-item">
                        <a type="button" class="btn btn-primary btn-block mb-2" href="{% url 'main:massage_list' %}"
                           style="width:50%">Список
                            рассылок &#9993;</a>
                    </li>
                    <li class="list-group-item">
                        <a type="button" class="btn btn-primary btn-block mb-2" href="{% url 'main:client_list' %}"
                           style="width:50%">Список
                            клиентов &#128104;</a>
                    </li>
                    <li class="list-group-item">
                        <a type="button" class="btn btn-primary btn-block mb-2" href="{% url 'main:settings_list' %}"
                           style="width:50%">Список
                            настроек &#127899;</a>
                    </li>
                    <li class="list-group-item">
                        <a type="button" class="btn btn-info btn-block mb-2" href="{% url 'main:report' %}"
                           style="width:50%">Отчет по
                            рассылкам &#128269;</a>
                    </li>
                    {%if user.is_staff%}
                    <li class="list-group-item">
                        <a type="button" class="btn btn-dark btn-block mb-2" href="{% url 'main:users_list' %}"
                           style="width:50%">Список пользователей &#128104;</a>
                    </li>
                    {%endif%}
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/massage_detail.html
{% extends 'main/base.html' %}
{% block content %}
<div class="col-6 mx-auto d-flex justify-content-center align-items-center">
    <br>
    <div class="card mb-4 box-shadow">

        <div class="card-header">
            <h4 class="my-0 font-weight-normal text-center">{{ object.head | title }}</h4>
        </div>

        <div class="card-body">
            <h4 class="card-title pricing-card-title text-center">{{object.body}}</h4>
            <ul class="list-unstyled mt-3 mb-4 text-start m-3 text-center">
                <li>Хозяин:</li>
                <li>{{object.user}}</li>
            </ul>
            <br>

            <a href="{% url 'main:massage_list'%}" type="button"
               class="btn btn-lg btn-block btn-outline-primary">Назад</a>

            {% if user.is_superuser or user == object.user %}
            <a href="{% url 'main:massage_update' object.pk %}" type="button"
               class="btn btn-lg btn-block btn-outline-primary">Редактировать</a>

            <a href="{% url 'main:massage_delete' object.pk %}" type="button"
               class="btn btn-lg btn-block btn-outline-danger">Удалить</a>
            {% endif %}

        </div>
    </div>
</div>
{% endblock %}

main/templates/main/massage_list.html
{% extends 'main/base.html' %}
{% block content %}
<div class="jumbotron  text-center">
    <h1 class="display-3">Список рассылок</h1>
    <p class="lead"></p>

    <div class="container text-center">
        <br>
        <div class="row">
            <div class="col">
                <ul class="list-group">
                    {% for object in object_list %}
                    <li class="list-group-item">
                        <a type="button" class="btn btn-outline-primary btn-block mb-2"
                           href="{% url 'main:massage_view' object.pk %}" style="width:50%">
                            {{ object.head }} : {{ object.body|slice:30}}
                            {%if object.user == user%}
                            <span style="color: green; float: right;">&#10003;</span>
                            {%endif%}
                        </a>
                    </li>
                    {% endfor %}
                    {% if not user.is_staff or user.is_superuser %}
                    <li class="list-group-item">
                        <a type="button" class="btn btn-success btn-block mb-2" href="{% url 'main:massage_create' %}"
                           style="width:25%">Создать
                            рассылку</a>
                    </li>
                    {%endif%}
                </ul>
                <a href="{% url 'main:index'%}" type="button"
                   class="btn btn-lg btn-block btn-outline-primary">Назад</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/settings_detail.html
{% extends 'main/base.html' %}
{% block content %}
<div class="col-6 mx-auto d-flex justify-content-center align-items-center">
    <br>
    <div class="card mb-4 box-shadow">

        <div class="card-header">
            <h4 class="my-0 font-weight-normal text-center">{{ object.time }}</h4>
        </div>

        <div class="card-body">
            <h4 class="card-title pricing-card-title text-center">{{object.frequency}} {{object.status}}</h4>
            <ul class="list-unstyled mt-3 mb-4 text-start m-3 text-center">
                <li>Хозяин:</li>
                <li>{{object.user}}</li>
                <li>Клиенты:</li>
                {%if object.client.all%}
                {% for cl in object.client.all %}
                <li> -- {{ cl }} --</li>
                {% endfor %}
                {%else%}
                ---------
                {%endif%}
                <li>Сообщения:</li>
                {%if object.massage.all%}
                {% for ms in object.massage.all %}
                <li> -- {{ ms }} --</li>
                {% endfor %}
                {%else%}
                ---------
                {%endif%}
            </ul>

            <a href="{% url 'main:settings_list'%}" type="button"
               class="btn btn-lg btn-block btn-outline-primary">Назад</a>

            {% if user.is_superuser or user == object.user %}
            <a href="{% url 'main:settings_update' object.pk %}" type="button"
               class="btn btn-lg btn-block btn-outline-primary">Редактировать</a>

            <a href="{% url 'main:settings_delete' object.pk %}" type="button"
               class="btn btn-lg btn-block btn-outline-danger">Удалить</a>
            {% endif %}

        </div>
    </div>
</div>
{% endblock %}

main/templates/main/user_detail.html
{% extends 'main/base.html' %}
{% block content %}
<div class="col-6 mx-auto d-flex justify-content-center align-items-center">
    <br>
    <div class="card mb-4 box-shadow">
        <img src="/media/{{ object.avatar }}" style="width:100%; height:300px;"/>
        <div class="card-header">
            <h4 class="my-0 font-weight-normal text-center">{{ object.email }}</h4>
        </div>

        <div class="card-body">
            <h4 class="card-title pricing-card-title text-center">{{object.first_name}} {{object.last_name}}</h4>
            <ul class="list-unstyled mt-3 mb-4 text-start m-3 text-center">
                <li>{{object.is_active}}</li>
            </ul>
            <a href="{% url 'main:user_update' object.pk %}" type="button"
               class="btn btn-lg btn-block btn-outline-primary">Редактировать</a>
            <a href="{% url 'main:users_list'%}" type="button"
               class="btn btn-lg btn-block btn-outline-primary">Назад</a>

        </div>
    </div>
</div>
{% endblock %}

main/templates/main/users_list.html
{% extends 'main/base.html' %}
{% block content %}
<div class="jumbotron  text-center">
    <h1 class="display-3">Список пользователей</h1>
    <p class="lead"></p>

    <div class="container text-center">
        <br>
        <div class="row">
            <div class="col">
                <ul class="list-group">
                    {% for object in object_list %}
                    {%if not object.is_staff%}
                    <li class="list-group-item">
                        <a type="button" class="btn btn-outline-primary btn-block mb-2"
                           href="{% url 'main:user_view' object.pk %}" style="width:50%">
                            {{ object.email }}
                        </a>
                    </li>
                    {%endif%}
                    {%endfor%}
                </ul>
                <a href="{% url 'main:index'%}" type="button"
                   class="btn btn-lg btn-block btn-outline-primary">Назад</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}